name: dhxn
description: A server app using the shelf package and Docker.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.0.0
  dio: ^5.0.0
  quiver: ^3.1.0
  shelf: ^1.1.0
  shelf_gzip: ^4.0.0
  shelf_hotreload: ^1.1.0
  shelf_router: ^1.0.0
  shelf_static: ^1.1.0
  timeago: ^3.2.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.15.0
